name: ci

on:
  push:
    branches: ['**']
    tags-ignore: ['**']
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION || '20' }}
      - run: npm install --no-audit --no-fund
      - run: npm run build
